friends/main/routes.py
from flask import Blueprint, render_template, g, session
from ..posts.models import Post


main = Blueprint('main', __name__)

@main.route('/')
def home():
  new_posts = Post.query.limit(5).all()
  return render_template('index.html', new_posts=new_posts)

friends/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  {% block head %}
    <title>Friends</title>
  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler mx-1" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-1">
        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Discover</a>
        {% if current_user.is_authenticated %} 
        <a class="nav-item nav-link" href="{{ url_for('posts.wall', wall_id=current_user.wall.id) }}">Wall</a>
        <a class="nav-item nav-link" href="{{ url_for('chat.chatroom') }}">Chatroom</a>
        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
        {% else %}
        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Create Account</a>
        {% endif %}
      </div>
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} 
      {% for category, message in messages %} 
        <div class="alert alert-{{category}} alter-dismissable fade show" role="alert">
          {{message}}
          <button type="button" class="btn-close" style="float:right;" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %} 
  {% endwith %}
  
  <div class="container">
    {% block content %} 
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

friends/templates/change_password.html
{% extends 'base.html' %}
{% block head %} 
  <title>Friends - Change Password</title>
{% endblock %} 
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-6 mx-auto bg-light border p-5 position-relative">
      <a class="position-absolute top-0 start-0 m-2 p-2" href="/wall/settings">&larr; Back</a>
      <h3 align="center">Change Password</h3>
      <form class="d-grid gap-4" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.password1.label() }}
          {% if form.password1.errors %}
            {{ form.password1(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password1.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password1(class="form-control", placeholder="Enter current password") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password2.label() }}
          {% if form.password2.errors %}
            <div class="invalid-feedback">
              {{ form.password2(class="form-control is-invalid") }}
              {% for error in form.password2.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password2(class="form-control", placeholder="Enter new password") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password3.label() }}
          {% if form.password3.errors %}
            {{ form.password3(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in password3.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password3(class="form-control", placeholder="Confirm new password") }}
          {% endif %}
        </div>
        {{ form.submit(class="btn btn-primary mt-3") }}
      </form>
    </div>
  </div>
{% endblock %}

friends/templates/chatroom.html
{% extends 'base.html' %}
{% block head %} 
   <title>Friends - Chatroom</title>
{% endblock %} 
{% block content %} 
   <style>
      ul {margin:0; padding:0;}
      li {list-style-type:none;}
   </style>
   <div class="row mt-5">
      <div class="col-md-6 mx-auto bg-light border p-5 position-relative">
         <ul class="my-2" id="messages"></ul>
         <div class="d-flex gap-0">
            <input class="form-control" type="text" id="message-input">
            <button id="message-send" class="btn btn-primary" type="button">Send</button>
         </div>
      </div>
   </div>
   <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
   <script type="text/javascript" charset="UTF-8" src="{{ url_for('static', filename='js/chat-socket.js') }}"></script>
{% endblock %}

friends/templates/conversations.html
{% extends 'base.html' %} 
{% block head %}
  <title>Friends - Conversations</title>
{% endblock %} 
{% block content %} 
{% endblock %}

friends/templates/edit_post.html
{% extends 'base.html' %}
{% block head %} 
  <title>Friends - Edit Post</title>
{% endblock %} 
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-10 mx-auto bg-light border p-5 position-relative">
      <a class="position-absolute top-0 start-0 m-2 p-2" href="/wall/{{current_user.wall.id}}">&larr; Back</a>
      <h3 align="center" class="mb-5">Edit Post</h3>
      <form class="d-grid gap-4" method="POST">
        {{ form.hidden_tag() }}
        {% if form.content.errors %}
          {{ form.content(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in post.content.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.content(class="form-control", style="resize:none;", cols="10", rows="10", id="content-input") }}
        {% endif %}
        {{ form.submit(class="btn btn-primary mt-3", value="Save Changes") }}
      </form>
    </div>
  </div>

  <script>
    document.getElementById("content-input").value = {{ post.content | tojson }}
  </script>
{% endblock %}

friends/templates/forgot_password.html
{% extends 'base.html' %} 
{% block head %} 
  <title>Friends - Forgot Password</title>
{% endblock %} 
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-6 mx-auto bg-lighgt border p-5">
      <form class="d-grid gap-3" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.email.label() }}
          {% if form.email.errors %}
            {{ form.email(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %} 
            {{ form.email(class="form-control", placeholder="Enter email for password reset") }}
          {% endif %}
        </div>
        {{ form.submit(class="btn btn-primary mt-3", value="Send Email") }}
      </form>
    </div>
  </div>
{% endblock %}

friends/templates/home.html
{% extends 'base.html' %} 
{% block head %} <title>Friends - Home</title> {% endblock %}
{% block content %} 
  <div class="row my-5">
    <h3 class="mb-5" align="center">Discover</h3>
    <div class="order-reverse gap-3">
      {% for post in new_posts %}
        <div class="col-md-6 mx-auto bg-light border p-5">
          <div class="d-flex align-items-center gap-2 my-2">
            {% if post.author.pic_id %}
              <img style="width:30px; height:30px;" class="img-responsive" src="{{ url_for('users.get_image', filename=post.author.pic_id) }}" alt="wall Picture">
            {% else %}
              <img style="width:30px; height:30px;" class="img-responsive" src="{{ url_for('static', filename='images/default.jpg') }}" alt="wall Picture">
            {% endif %}
            <h4>
              <a href="/wall/{{ post.author.wall.id }}">{{ post.author.screen_name }}</a>
            </h4>
            <small class="text-muted">
              {% if post.changes %}
                <i>Edited</i> {{post.date_posted.strftime("%A, %b %d '%y, %I:%M %p")}}
              {% else %}
                {{post.date_posted.strftime("%A, %b %d '%y")}}
              {% endif %}
            </small>
          </div>
          <div class="mx-1">{{ post.content }}</div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

friends/templates/index.html
{% extends 'base.html' %} 
{% block head %} <title>Friends - Home</title> {% endblock %}
{% block content %} 
  <div class="row my-5">
    <h3 class="mb-5" align="center">Discover</h3>
    <div class="order-reverse gap-3">
      {% for post in new_posts %}
        <div class="col-md-6 mx-auto bg-light border p-5">
          <div class="d-flex align-items-center gap-2 my-2">
            {% if post.author.pic_id %}
              <img style="width:30px; height:30px;" class="img-responsive" src="{{ url_for('users.get_image', filename=post.author.pic_id) }}" alt="wall Picture">
            {% else %}
              <img style="width:30px; height:30px;" class="img-responsive" src="{{ url_for('static', filename='images/default.jpg') }}" alt="wall Picture">
            {% endif %}
            <h4>
              <a href="/wall/{{ post.author.wall.id }}">{{ post.author.screen_name }}</a>
            </h4>
            <small class="text-muted">
              {% if post.changes %}
                <i>Edited</i> {{post.date_posted.strftime("%A, %b %d '%y, %I:%M %p")}}
              {% else %}
                {{post.date_posted.strftime("%A, %b %d '%y")}}
              {% endif %}
            </small>
          </div>
          <div class="mx-1">{{ post.content }}</div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

friends/templates/login.html
{% extends 'base.html' %} 
{% block head %} 
  <title>Friends - Login</title>
{% endblock %}
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-6 mx-auto mt-5 p-5 bg-light border">
      <h3 align="center">Login</h3>
      <form class="d-grid gap-2" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.email.label() }}
          {% if form.email.errors %} 
            {{ form.email(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %} 
            {{ form.email(class="form-control", placeholder="Enter email") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label() }}
          {% if form.password.errors %}
            {{ form.password(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control", placeholder="Enter password") }}
          {% endif %}
          <small class="text-muted"><a href="/reset-password">Forgot Pasword?</a></small>
        </div>
        {{ form.submit(class="btn btn-primary mt-3") }}
        <small class="text-muted">Need An Account?
          <a href="{{ url_for('users.register') }}">Create One Here</a>
        </small>
      </form>
    </div>
  </div>
{% endblock %}

friends/templates/profile.html
{% extends 'base.html' %} 
{% block head %} 
  <script defer src="{{ url_for('static', filename='js/profile.js') }}"></script>
  <title>Friends - Profile</title>
{% endblock %} 
{% block content %} 
  <style>
    img {display: block; max-width: 100%; height: auto; object-fit: cover; border-radius: 50%;}
    a {text-decoration: none;}
    .order-reverse {display: flex; flex-direction: column-reverse;}
  </style>

  <div class="row m-5">
    <div class="col-md-10 mx-auto bg-light border position-relative p-5">
      <div class="d-flex align-items-center justify-content-center gap-3">
        {% if user.pic_id %}
          <img style="width:30px; height:30px;"class="img-responsive" src="{{ url_for('views.get_image', filename=user.pic_id) }}" alt="Profile Picture">
        {% else %} 
          <img style="width:30px; height:30px;"class="img-responsive" src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile Picture">
        {% endif %}
        <h3>{{user.screen_name}}'s Profile</h3>
        {% if is_wall_of_current_user %}
          <a class="position-absolute end-0 mx-5 p-3" href="/profile/settings">Settings</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row mx-5">
    <div class="col-md-10 mx-auto bg-light border p-5 mb-5">
      {% if current_user.is_authenticated %}
        <form class="d-grid gap-3" method="POST">
          {{ form.hidden_tag() }}
          {% if form.post_content.errors %}
            {% if is_wall_of_current_user %}
              {{ form.post_content(class="form-control is-invalid", cols="10", rows="5", placeholder="Share what's new...", style="resize:none") }}
            {% else %}
              {{ form.post_content(class="form-control is-invalid", cols="10", rows="5", placeholder="Write to " + user.screen_name + "'s wall...", style="resize:none") }}
            {% endif %}
            <div class="invalid-feedback">
              {% for error in form.post_content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %} 
            {% if is_wall_of_current_user %}
              {{ form.post_content(class="form-control", cols="10", rows="5", placeholder="Share what's new...", style="resize:none") }}
            {% else %}
              {{ form.post_content(class="form-control", cols="10", rows="5", placeholder="Write to " + user.screen_name + "'s wall...", style="resize:none") }}
            {% endif %}
          {% endif %}
          {{ form.submit(class="btn btn-primary mt-2") }}
        </form>
        <hr>
      {% endif %}

      {% if posts %}
        <div class="order-reverse position-relative">
          {% for post in posts %}
            <div class="py-3">
              {% if (post.author_id == current_user.id) or (wall.user_id == current_user.id) %}
                <button class="btn text-danger position-absolute end-0" type="button" 
                onclick="deletePost({{ wall.user_id }}, {{ post.id }}, )"
                >Delete</button>
              {% endif %}
              <div class="d-flex align-items-center gap-2 my-2">
                {% if get_author(post.author_id).pic_id %}
                  <img style="width:30px; height:30px;"class="img-responsive" src="{{ url_for('views.get_image', filename=get_author(post.author_id).pic_id) }}" alt="Profile Picture">
                {% else %} 
                  <img style="width:30px; height:30px;"class="img-responsive" src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile Picture">
                {% endif %}
                <a href="/profile/{{post.author_id}}">
                  <h4>{{get_author(post.author_id).screen_name}}</h4>
                </a>
                <small class="text-muted">{{post.date_posted.strftime("%A, %b %d '%y")}}</small>
              </div>
              <div class="px-1">
                {{post.content}}
              </div>
              <br>
              {% if current_user.is_authenticated %}
                <div class="d-flex gap-1">
                  <input class="form-control w-50" type="text" id="comment-box-{{post.id}}">
                  <button class="btn btn-secondary" type="button"
                  onclick="addComment({{ wall.user_id }}, {{ post.id }}, {{ current_user.id }})"
                  >Add A Comment</button>
                </div>
              {% endif %}
              <div class="order-reverse">
                {% for comment in post.comments %}
                  <div class="border-bottom p-2">
                    <div class="d-flex gap-2">
                      <a href="/profile/{{comment.author_id}}">{{get_author(comment.author_id).screen_name}}</a> {{comment.content}}
                    </div>
                    <small class="text-muted">{{comment.date_posted.strftime("%A, %b %d '%y")}}</small>
                  </div>
                {% endfor %}
              </div>
              <hr>
            </div>
          {% endfor %}
        </div>
      {% else %} 
        <h5 align="center" class="text-muted mt-5">No posts to show</h5>
      {% endif %}
    </div>
  </div>
{% endblock %}

friends/templates/request_reset.html
{% extends 'base.html' %} 
{% block head %} 
  <title>Friends - Forgot Password</title>
{% endblock %} 
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-6 mx-auto bg-lighgt border p-5 position-relative">
      <a class="position-absolute top-0 start-0 m-2 p-2" href="{{ url_for('users.login') }}">&larr; Back</a>
      <h3 align="center" class="mb-3">Request Password Reset</h3>
      <form class="d-grid gap-3" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.email.label() }}
          {% if form.email.errors %}
            {{ form.email(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %} 
            {{ form.email(class="form-control", placeholder="Enter email for password reset") }}
          {% endif %}
        </div>
        {{ form.submit(class="btn btn-primary mt-3", value="Send Email") }}
      </form>
    </div>
  </div>
{% endblock %}

friends/templates/reset_password.html
{% extends 'base.html' %}
{% block head %} 
  <title>Friends - Reset Password</title>
{% endblock %} 
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-6 mx-auto bg-light border p-5 position-relative">
      <a class="position-absolute top-0 start-0 m-2 p-2" href="/wall/settings">&larr; Back</a>
      <h3 align="center">Reset Password</h3>
      <form class="d-grid gap-4" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.password1.label() }}
          {% if form.password1.errors %}
            <div class="invalid-feedback">
              {{ form.password1(class="form-control is-invalid") }}
              {% for error in form.password1.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password1(class="form-control", placeholder="Enter new password") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password2.label() }}
          {% if form.password2.errors %}
            {{ form.password2(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password2.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password2(class="form-control", placeholder="Confirm new password") }}
          {% endif %}
        </div>
        {{ form.submit(class="btn btn-primary mt-3", value="Reset Password") }}
      </form>
    </div>
  </div>
{% endblock %}

friends/templates/settings.html
{% extends 'base.html' %} 
{% block head %} 
  <title>Friends - Wall Settings</title>
{% endblock %} 
{% block content %} 
  <div class="row mt-5">
    <div class="col-md-6 mx-auto bg-light border p-5 position-relative">
      <a class="position-absolute top-0 start-0 m-2 p-2" href="/wall/{{current_user.wall.id}}">&larr; Back</a>
      <h3 align="center">Settings</h3>
      <form class="d-grid gap-4" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.pic_upload.label() }}
          {% if form.pic_upload.errors %} 
            {{ form.pic_upload(class="form-control is-invalid", accept="image/*") }}
            <div class="invalid-feedback">
              {% for error in form.pic_upload.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.pic_upload(class="form-control", accept="image/*") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.screen_name.label() }}
          {% if form.screen_name.errors %} 
            {{ form.screen_name(class="form-control is-invalid", value=current_user.screen_name) }}
            <div class="invalid-feedback">
              {% for error in form.screen_name.errors %} 
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.screen_name(class="form-control", value=current_user.screen_name) }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.email.label() }}
          {% if form.email.errors %} 
            {{ form.email(class="form-control is-invalid", value=current_user.email) }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %} 
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control", value=current_user.email) }}
          {% endif %}
        </div>
        <button class="btn btn-secondary" type="button" onclick=window.location.href='/wall/settings/password'>Change Password</button>
        {{ form.submit(class="btn btn-primary mt-3") }}
      </form>
    </div>
  </div>
{% endblock %}

friends/templates/wall.html
{% extends 'base.html' %} 
{% block head %} 
  <script defer src="{{ url_for('static', filename='js/wall.js') }}"></script>
  <title>Friends - Wall</title>
{% endblock %} 
{% block content %} 
  <div class="row m-5">
    <div class="col-md-10 mx-auto bg-light border position-relative p-5">
      <div class="d-flex align-items-center justify-content-center gap-4">
        {% if user.pic_id %}
          <img style="width:30px; height:30px;"class="img-responsive" src="{{ url_for('users.get_image', filename=user.pic_id) }}" alt="wall Picture">
        {% else %} 
          <img style="width:30px; height:30px;"class="img-responsive" src="{{ url_for('static', filename='images/default.jpg') }}" alt="wall Picture">
        {% endif %}
        <h3>{{user.screen_name}}'s Wall</h3>
        {% if is_wall_of_current_user %}
          <a class="position-absolute end-0 mx-5 p-3" href="{{ url_for('users.settings') }}">Settings</a>
        {% else %} 
          <a class="position-absolute start-0 mx-5 p-3" href="">Message</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row mx-5">
    <div class="col-md-10 mx-auto bg-light border p-5 mb-5">
      {% if current_user.is_authenticated %}
        <form class="d-grid gap-4" method="POST">
          {{ form.hidden_tag() }}
          {% if form.content.errors %}
            {% if is_wall_of_current_user %}
              {{ form.content(class="form-control is-invalid", cols="10", rows="5", placeholder="Share what's new...", style="resize:none") }}
            {% else %}
              {{ form.content(class="form-control is-invalid", cols="10", rows="5", placeholder="Write to " + user.screen_name + "'s wall...", style="resize:none") }}
            {% endif %}
            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %} 
            {% if is_wall_of_current_user %}
              {{ form.content(class="form-control", cols="10", rows="5", placeholder="Share what's new...", style="resize:none") }}
            {% else %}
              {{ form.content(class="form-control", cols="10", rows="5", placeholder="Write to " + user.screen_name + "'s wall...", style="resize:none") }}
            {% endif %}
          {% endif %}
          {{ form.submit(class="btn btn-primary mt-2") }}
        </form>
        <hr>
      {% endif %}

      {% if posts %}
        <div class="order-reverse position-relative">
          {% for post in posts %}
            <div class="py-3">
              {% if (post.author_id == current_user.id) or (wall.user_id == current_user.id) %}
                <div class="d-flex position-absolute end-0">
                  <button class="btn text-info" type="button" 
                  onclick=window.location.href="/wall/edit-post/{{post.id}}"
                  >Edit</button>
                  <button style="display:block;" class="btn text-danger" type="button"
                  onclick="deletePost({{ wall.id }}, {{ post.id }}, )"
                  >Delete</button>
                </div>
              {% endif %}
              <div class="d-flex align-items-center gap-2 my-2">
                {% if post.author.pic_id %}
                  <img style="width:30px; height:30px;" class="img-responsive" src="{{ url_for('users.get_image', filename=post.author.pic_id) }}" alt="wall Picture">
                {% else %} 
                  <img style="width:30px; height:30px;" class="img-responsive" src="{{ url_for('static', filename='images/default.jpg') }}" alt="wall Picture">
                {% endif %}
                <a href="/wall/{{post.author.wall.id}}">
                  <h4>{{post.author.screen_name}}</h4>
                </a>
                <small class="text-muted">
                  {% if post.changes %}
                    <i>Edited</i> {{post.date_posted.strftime("%A, %b %d '%y, %I:%M %p")}}
                  {% else %}
                    {{post.date_posted.strftime("%A, %b %d '%y")}}
                  {% endif %}
                </small>
              </div>
              <div class="mx-1">
                {{post.content}}
              </div>
              <br>
              {% if current_user.is_authenticated %}
                <div class="d-flex gap-1">
                  <input class="form-control w-50" type="text" id="comment-input-{{post.id}}">
                  <button class="btn btn-secondary" type="button"
                  onclick="addComment({{ wall.id }}, {{ post.id }}, {{ current_user.id }})"
                  >Add A Comment</button>
                </div>
              {% endif %}
              <div class="order-reverse">
                {% for comment in post.comments %}
                  <div class="border-bottom p-2">
                    <div class="d-flex gap-2">
                      <a href="/wall/{{comment.author.wall.id}}">{{comment.author.screen_name}}</a> 
                      {{comment.content}}
                    </div>
                    <small class="text-muted">{{comment.date_posted.strftime("%A, %b %d '%y")}}</small>
                    {% if (comment.author == current_user) or (comment.post.wall.user == current_user) %}
                      <button class="btn text-danger" type="button" onclick="deleteComment({{ wall.id }}, {{ comment.id }})">
                        <small>Delete</small>
                      </button>
                    {% endif %}
                  </div>
                {% endfor %}
              </div>
              <hr>
            </div>
          {% endfor %}
        </div>
      {% else %} 
        <h5 align="center" class="text-muted mt-5">No posts to show</h5>
      {% endif %}
    </div>
  </div>
{% endblock %}