website/models.py
from flask_login import UserMixin
from .extensions import db
from datetime import datetime

class User(db.Model, UserMixin):
  id = db.Column(db.Integer, primary_key=True)
  screen_name = db.Column(db.String(20), nullable=False)
  email = db.Column(db.String(255), unique=True, nullable=False)
  password = db.Column(db.String(255), nullable=False)
  pic_url = db.Column(db.String(1000), default='default.jpg')
  wall = db.relationship('Wall', cascade='all,delete')
  authored_posts = db.relationship('Post', backref='author', lazy=True)

  def __repr__(self):
    return f'<User {self.email}>'

class Wall(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
  user = db.relationship('User')
  posts = db.relationship('Post', backref='wall', lazy=True, cascade="all,delete")
  
class Post(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  content = db.Column(db.String(10000), nullable=False)
  date_posted = db.Column(db.DateTime, default=datetime.utcnow())
  author_id = db.Column(db.Integer, db.ForeignKey('user.id'))
  wall_id = db.Column(db.Integer, db.ForeignKey('wall.id')) # The wall id refers to which wall the post was created at

website/__init__.py
from flask import Flask
from .extensions import db, login_manager, migrate


def create_app(config_file='settings.py'):
  app = Flask(__name__)
  app.config.from_pyfile(config_file)
  db.init_app(app)

  login_manager.login_view = 'auth.login'
  login_manager.init_app(app)

  from .views import views
  app.register_blueprint(views)
  from .auth import auth
  app.register_blueprint(auth)

  from .models import User
  db.create_all(app=app)

  migrate.init_app(app, db)

  @login_manager.user_loader
  def load_user(user_id):
    return User.query.get(user_id)

  return app

website/auth.py
from flask import Blueprint, request, redirect, render_template, flash, url_for
from flask_login import login_required, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash

from .models import User, Wall
from .extensions import db


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
  if request.method == 'POST':
    email = request.form.get('email')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()
    if not user:
      flash('User does not exist!', category='danger')
      return redirect(url_for('auth.login'))

    if check_password_hash(user.password, password):
      login_user(user, remember=False)
      flash(f'Successfully logged in as {user.screen_name}!', category='success')
      return redirect(url_for('views.home'))
    else:
      flash('Incorrect password', category='danger')
      return redirect(url_for('auth.login'))

  return render_template('login.html')

@auth.route('/register', methods=['GET', 'POST'])
def register():
  if request.method == 'POST':
    if request.form['password1'] != request.form['password2']:
      flash('Passwords didn\'t match', category='danger')
      return redirect(url_for('auth.register'))

    screen_name = request.form['screen-name']
    email = request.form['email']
    password = request.form['password2']

    rules = [
      len(password) > 7,
      any(char.isupper() for char in password),
      any(char.islower() for char in password),
      any(char.isdigit() for char in password)
    ]

    if not all(rules):
      flash('Password must have one uppercase letter, one lower case letter, one number, and be at least 8 characters in length', category='danger')
      return redirect(url_for('auth.register'))

    new_user = User(screen_name=screen_name, email=email, password=generate_password_hash(password))
    db.session.add(new_user)
    db.session.commit()

    login_user(new_user, remember=False)
    flash(f'Account created for {new_user.screen_name}!', category='success')
    return redirect(url_for('views.home'))

  return render_template('register.html')

@auth.route('/logout')
@login_required
def logout():
  logout_user()
  flash('You have been logged out', category='info')
  return redirect(url_for('views.home'))

website/views.py
from os import path
from flask import Blueprint, render_template, request, send_from_directory
from flask.helpers import url_for
from werkzeug.utils import redirect
from .models import User, Wall, Post
from flask_login import current_user
from .extensions import db


views = Blueprint('views', __name__)

@views.route('/')
def home():
  return render_template('home.html')

@views.route('/profile/<int:user_id>', methods=['GET', 'POST'])
def profile(user_id):
  if request.method == 'POST':
    post_content = request.form['post-content']
    new_post = Post(content=post_content, author_id=current_user.id, wall_id=user_id)
    db.session.add(new_post)
    db.session.commit()
    return redirect(url_for('views.profile', user_id=user_id))
  wall = Wall.query.filter_by(user_id=user_id).first()
  if not wall:
    wall = Wall(user_id=user_id)
    db.session.add(wall)
    db.session.commit()
  
  user = User.query.get_or_404(user_id)
  posts = wall.posts

  try:
    is_wall_of_current_user = user_id == current_user.id
  except:
    is_wall_of_current_user = False

  def get_author(author_id):
    return User.query.get_or_404(author_id)

  context = {
    'user': user,
    'wall': wall,
    'posts': posts,
    'get_author': get_author,
    'is_wall_of_current_user': is_wall_of_current_user
  }

  return render_template('profile.html', **context)

@views.route('/profile/settings')
def settings():
  return render_template('settings.html')

@views.route('/file_uploads/images/<filename>')
def upload_image(filename):
  return send_from_directory('file_uploads/images', filename, environ=r'C:\Users\sethm\Desktop\Ongoing\friends\website\file_uploads')

website/templates/profile.html
{% extends 'base.html' %} 
{% block head %} 
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <title>Friends - Profile</title>
{% endblock %} 
{% block content %} 
  <span>
    <img src="{{ url_for('views.upload_image', filename='default.jpg') }}" alt="{{user.screen_name}}'s dynamic profile picture">
    {% if is_wall_of_current_user %}
      <h3 align="center" class="mt-5 mb-5">{{user.screen_name}}'s Profile <a href="/profile/settings">Settings</a></h3>
    {% else %}
      <h3 align="center" class="mt-5 mb-5">{{user.screen_name}}'s Profile</h3>
    {% endif %}
  </span>
  {% if current_user.is_authenticated %}
    <form method="POST">
      {% if is_wall_of_current_user %}
        <textarea style="resize:none;" class="form-control" name="post-content" cols="10" rows="5" placeholder="Share what's new..."></textarea>
      {% else %} 
        <textarea style="resize:none;" class="form-control" name="post-content" cols="10" rows="5" placeholder="Write to {{user.screen_name}}'s wall..."></textarea>
      {% endif %}
      <button class="btn btn-primary mt-2" type="submit">Post</button>
    </form>
  {% endif %}
  {% if posts %} 
    <div class="wall-posts mt-3 pb-5">
      {% for post in posts %}
        <div class="media">
          <img class="mr-3" src="..." alt="Generic placeholder image">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="/profile/{{post.author_id}}">{{get_author(post.author_id).screen_name}}</a>
            </h5>
            {{post.content}}
          </div>
        </div>
        <hr>
      {% endfor %}
    </div>
  {% else %}
    <div>User has no posts!</div>
  {% endif %}
{% endblock %}

website/templates/settings.html
{% extends 'base.html' %} 
{% block head %} 
  <title>Friends - Profile Settings</title>
{% endblock %} 
{% block content %} 
  <h3 align="center" class="mt-5">Settings</h3>
  <form method="POST">
    <div class="form-group mb-3">
      <label for="profile-pic">Change Pic</label>
      <input class="form-control" type="file" name="profile-pic" id="profile-pic">
    </div>
    <div class="form-group mb-3">
      <label for="screen-name">Screen Name</label>
      <input class="form-control" type="text" name="screen-name" id="screen-name" placeholder="Enter screen name">
    </div>
    <div class="form-group mb-3">
      <label for="email">Email</label>
      <input class="form-control" type="email" name="email" id="email" placeholder="Enter email">
    </div>
    <input class="btn btn-primary" type="submit" value="Save Changes">
  </form>
{% endblock %}